"""create notes table

Revision ID: 2f2f8f43337f
Revises: 082edd51a409
Create Date: 2026-08-05 15:22:45.062021

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2f2f8f43337f"
down_revision: Union[str, Sequence[str], None] = "082edd51a409"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
