"""update memories table

Revision ID: 6d1bfccc71ef
Revises: ae6afdf6bbfe
Create Date: 2026-08-04 17:41:44.146969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6d1bfccc71ef"
down_revision: Union[str, Sequence[str], None] = "ae6afdf6bbfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memories", sa.Column("content", sa.Text(), nullable=True))
    op.add_column("memories", sa.Column("source", sa.String(length=50), nullable=True))
    op.execute(sa.text("UPDATE memories SET content = value, source = 'chat'"))
    op.alter_column("memories", "content", nullable=False)
    op.alter_column("memories", "source", nullable=False)
    op.drop_column("memories", "key")
    op.drop_column("memories", "value")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memories", sa.Column("value", sa.TEXT(), nullable=True))
    op.add_column("memories", sa.Column("key", sa.VARCHAR(length=255), nullable=True))
    # The removed legacy key cannot be reconstructed; retain all memory text.
    op.execute(
        sa.text(
            "UPDATE memories SET value = content, key = 'memory_' || CAST(id AS VARCHAR)"
        )
    )
    op.alter_column("memories", "value", nullable=False)
    op.alter_column("memories", "key", nullable=False)
    op.drop_column("memories", "source")
    op.drop_column("memories", "content")
    # ### end Alembic commands ###
